### PR TITLE
fix compatability issue in node version >=6.0.0

### LINKED ISSUE #3: utf7 does not work in node verson >=6.0.0
> $ node
> \> var u=require('utf7').imap;
> undefined
> \> u.encode('你好')
> **Error: If encoding is specified then the first argument must be a string**
>     at new Buffer (buffer.js:106:13)
>     at encode (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:4:13)
>     at /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:77:39
>     at RegExp.[Symbol.replace] (native)
>     at String.replace (native)
>     at Object.exports.imap.encode (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:75:36)
>     at repl:1:3
>     at REPLServer.defaultEval (repl.js:272:27)
>     at bound (domain.js:280:14)
>     at REPLServer.runBound [as eval] (domain.js:293:12)
> \>

### PR DESCRIPTION
**Pull request by truebit**
I am a newbie in nodejs.
I tried to fixes #3 . In my opinion, it works. maybe it's not good enough. please take a look.

### CODE REVIEW

**Comment by jlipps** [comment]
@kkaefer can you review this? we rely on utf7 and would love to have this issue with node 6 resolved.

**Comment by kkaefer** [comment]
Commited with changes in fc5bf2f9dc6e7d6977e2f775954e0035e87988d6

**Comment by kkaefer** [comment]
Thanks, @truebit!

**Comment by jlipps** [comment]
Thanks @kkaefer! Will there be an NPM publish soon so we can take advantage of this fix?

**Comment by kkaefer** [comment]
Published version 1.0.1

**Comment by jlipps** [comment]
Excellent, thank you so much.

**Comment by ahelmberger** [comment]
Thanks!

**Pull request closed without merging**
